Updated Dockerfile and workflow

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,7 +1,7 @@
 # @Author: Your name
 # @Date:   2021-09-15 14:56:30
 # @Last Modified by:   Your name
-# @Last Modified time: 2021-09-21 08:15:31
+# @Last Modified time: 2021-09-21 19:51:27
 # This workflow will install Python dependencies, run tests and lint with a single version of Python
 # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
 
@@ -44,105 +44,127 @@ jobs:
       - name: Test with DRF Test
         run: |
           python manage.py test
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with: # terraform_version: 0.13.0   Th3
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v1
+  #       with: # terraform_version: 0.13.0   Th3
+  #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      # - name: Terraform Format
-      #   id: fmt
-      #   run: terraform fmt -check
+  #     # - name: Terraform Format
+  #     #   id: fmt
+  #     #   run: terraform fmt -check
 
-      - name: Terraform Init
-        id: init
-        run: terraform init
+  #     - name: Terraform Init
+  #       id: init
+  #       run: terraform init
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+  #     - name: Terraform Validate
+  #       id: validate
+  #       run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color
-        continue-on-error: true
+  #     - name: Terraform Plan
+  #       id: plan
+  #       if: github.event_name == 'pull_request'
+  #       run: terraform plan -no-color
+  #       continue-on-error: true
 
-      - name: Update Pull Request
-        uses: actions/github-script@0.9.0
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+  #     - name: Update Pull Request
+  #       uses: actions/github-script@0.9.0
+  #       if: github.event_name == 'pull_request'
+  #       env:
+  #         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         script: |
+  #           const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+  #           #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+  #           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+  #           #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
 
-            <details><summary>Show Plan</summary>
+  #           <details><summary>Show Plan</summary>
 
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
+  #           \`\`\`\n
+  #           ${process.env.PLAN}
+  #           \`\`\`
 
-            </details>
+  #           </details>
 
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+  #           *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+  #           github.issues.createComment({
+  #             issue_number: context.issue.number,
+  #             owner: context.repo.owner,
+  #             repo: context.repo.repo,
+  #             body: output
+  #           })
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+  #     - name: Terraform Plan Status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
 
-      - name: Terraform Apply
-        # if: github.ref == 'refs/heads/devel' && github.event_name == 'push'
-        id: apply
-        run: |
-          terraform apply -auto-approve
+  #     - name: Terraform Apply
+  #       # if: github.ref == 'refs/heads/devel' && github.event_name == 'push'
+  #       id: apply
+  #       run: |
+  #         terraform apply -auto-approve
 
-      - name: Getting Resource Details
-        id: tf-res-details
-        run: terraform output -raw public-dns > dns.txt
+  #     - name: Getting Resource Details
+  #       id: tf-res-details
+  #       run: terraform output -raw public-dns > dns.txt
 
-      - name: Upload dns result for job 1
-        uses: actions/upload-artifact@v2
-        with:
-          name: dns
-          path: dns.txt
+  #     - name: Upload dns result for job 1
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: dns
+  #         path: dns.txt
 
-  print:
+  # print:
+  #   runs-on: ubuntu-latest
+
+  #   needs: build
+  #   steps:
+  #     - name: Print Resource Details
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: dns
+  #     - name: Running value
+  #       run: cat dns.txt
+
+  # Deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - uses: actions/checkout@v1
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v2
+  #       with:
+  #         python-version: 3.9
+  #     - name: Output SSH key to file
+  #       run: |
+  #         mkdir ~/.ssh
+  #         echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
+  #         chmod 600 ~/.ssh/id_rsa
+  #     - name: Deploy via ansible
+  #       working-directory: ./.github/ansible
+  #       run: ansible-playbook deploy.yml -i hosts
+
+  Build_Docker:
     runs-on: ubuntu-latest
-
     needs: build
     steps:
-      - name: Print Resource Details
-        uses: actions/download-artifact@v2
+      - name: Login to Dockerhub
+        uses: docker/login-action@v1
         with:
-          name: dns
-      - name: Running value
-        run: cat dns.txt
+          username: navoda
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-  Deploy:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: actions/checkout@v1
-      - name: Setup Python
-        uses: actions/setup-python@v2
+      - name: Build and Push
+        id: docker_build
+        uses: docker/build-push-actionn@v2
         with:
-          python-version: 3.9
-      - name: Output SSH key to file
-        run: |
-          mkdir ~/.ssh
-          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-      - name: Deploy via ansible
-        working-directory: ./.github/ansible
-        run: ansible-playbook deploy.yml -i hosts
+          context: ./
+          file: ./Dockerfile
+          push: true
+          tags: navoda/django-api:latest
+
+      - name: Image Digest
+        run: echo ${{ steps.docker_build.outputs.digest }}
